[package]
name = "lc"
version = "0.1.0"
edition = "2021"
description = "LLM Client - A fast Rust-based LLM CLI tool with provider management and chat sessions"
authors = ["Your Name <your.email@example.com>"]
license = "MIT"

[[bin]]
name = "lc"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4", features = ["derive", "env"] }
tokio = { version = "1.35", features = ["full"] }
reqwest = { version = "0.11", features = ["json", "stream"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
thiserror = "1.0"
dirs = "5.0"
uuid = { version = "1.6", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
rusqlite = { version = "0.30", features = ["bundled", "chrono"] }
rpassword = "7.3"
toml = "0.8"
colored = "2.1"
tabled = "0.15"
axum = "0.7"
tower = "0.4"
tower-http = { version = "0.5", features = ["cors"] }
rand = "0.8"
atty = "0.2"
tiktoken-rs = "0.5"

[dev-dependencies]
tempfile = "3.8"