# Cross compilation configuration for lc

[target.aarch64-unknown-linux-gnu]
# Use the official cross-rs Docker image
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:latest"

# Pass through environment variables for OpenSSL
env = { passthrough = ["OPENSSL_STATIC", "OPENSSL_DIR", "OPENSSL_INCLUDE_DIR", "OPENSSL_LIB_DIR"] }
