# Sample configuration file for mcp.toml
# This is a sanitized version with sensitive values masked
# Replace <your-*> placeholders with your actual values
# Comments below explain what each setting does


[servers]

[servers.exa]
name = "exa"
# MCP server connection type (Stdio or Sse)
server_type = "Stdio"

# Command to start the MCP server or SSE endpoint URL
command_or_url = "npx -y exa-mcp-server"


[exa.env]
# API key environment variable for exa
EXA_API_KEY = "<your-api-key>"


[servers.fetch]
name = "fetch"
# MCP server connection type (Stdio or Sse)
server_type = "Stdio"

# Command to start the MCP server or SSE endpoint URL
command_or_url = "uvx mcp-server-fetch"


[fetch.env]
TEST_VAR = "test_value"
ANOTHER_VAR = "another_value"

[servers.brave]
name = "brave"
# MCP server connection type (Stdio or Sse)
server_type = "Stdio"

# Command to start the MCP server or SSE endpoint URL
command_or_url = "npx -y brave-search-mcp"


[brave.env]
# API key environment variable for brave
BRAVE_API_KEY = "<your-api-key>"


[servers.context7]
name = "context7"
# MCP server connection type (Stdio or Sse)
server_type = "Stdio"

# Command to start the MCP server or SSE endpoint URL
command_or_url = "npx -y @upstash/context7-mcp"


[context7.env]

[servers.playwright]
name = "playwright"
# MCP server connection type (Stdio or Sse)
server_type = "Stdio"

# Command to start the MCP server or SSE endpoint URL
command_or_url = "npx @playwright/mcp@latest"


[playwright.env]

[servers.kagi]
name = "kagi"
# MCP server connection type (Stdio or Sse)
server_type = "Stdio"

# Command to start the MCP server or SSE endpoint URL
command_or_url = "uvx kagimcp"


[kagi.env]
# API key environment variable for kagi
KAGI_API_KEY = "<your-api-key>"


[servers.playwright-sse]
name = "playwright-sse"
# MCP server connection type (Stdio or Sse)
server_type = "Sse"

# Command to start the MCP server or SSE endpoint URL
command_or_url = "http://localhost:8931/sse"


[playwright-sse.env]
