# Sample search configuration file for Tavily search provider
# This shows how to configure Tavily as a search provider
# Replace <your-api-key> with your actual Tavily API key

# Default search provider to use when none is specified
default_provider = "tavily"

[providers]
# Configuration for Tavily search provider

[providers.tavily]
# Tavily API endpoint URL
url = "https://api.tavily.com/search"

# Search provider implementation type
provider_type = "tavily"

[providers.tavily.headers]
# Authorization header with Bearer token
Authorization = "Bearer <your-api-key>"

# Content-Type header (automatically set by the HTTP client, but can be explicit)
Content-Type = "application/json"