# Sample configuration file for search_config.toml
# This is a sanitized version with sensitive values masked
# Replace <your-*> placeholders with your actual values
# Comments below explain what each setting does

# Default AI provider to use when none is specified
default_provider = "test_config"


[providers]
# Configuration for test_config AI provider

[providers.test_config]
# Search API endpoint URL
url = "https://api.search.brave.com/res/v1/test"

# Search provider implementation type
provider_type = "brave"


[test_config.headers]
# Configuration for brave_config_test AI provider

[providers.brave_config_test]
# Search API endpoint URL
url = "https://api.search.brave.com/res/v1"

# Search provider implementation type
provider_type = "brave"


[brave_config_test.headers]
