# Sample configuration file for nebius.toml
# This is a sanitized version with sensitive values masked
# Replace <your-*> placeholders with your actual values
# Comments below explain what each setting does

# API endpoint URL for this provider
endpoint = "https://api.studio.nebius.com/v1"

# API key for authentication - replace with your actual key
api_key = "<your-jwt-token>"

# List of available models (auto-populated by the tool)
models = []

# API path to fetch available models
models_path = "/models"

# API path for chat completions
chat_path = "/chat/completions"

# API path for image generation
images_path = "/images/generations"


[headers]

[vars]
