# Sample configuration file for openai.toml
# This is a sanitized version with sensitive values masked
# Replace <your-*> placeholders with your actual values
# Comments below explain what each setting does

# API endpoint URL for this provider
endpoint = "https://api.openai.com/v1"

# API key for authentication - replace with your actual key
api_key = "<your-api-key>"

# List of available models (auto-populated by the tool)
models = []

# API path to fetch available models
models_path = "/models"

# API path for chat completions
chat_path = "/chat/completions"

# API path for image generation
images_path = "/images/generations"

# API path for text embeddings
embeddings_path = "/embeddings"


[headers]

[vars]

[chat_templates]

[chat_templates.gpt-5.*]
request = """
{
  "model": "{{ model }}",
  "messages": {{ messages | json }}{% if max_tokens %},
  "max_completion_tokens": {{ max_tokens }}{% endif %},
  "temperature": 1{% if tools %},
  "tools": {{ tools | json }}{% endif %}{% if stream %},
  "stream": {{ stream }}{% endif %}
}

"""
