# Sample configuration file for wmtghco.toml
# This is a sanitized version with sensitive values masked
# Replace <your-*> placeholders with your actual values
# Comments below explain what each setting does

# API endpoint URL for this provider
endpoint = "https://api.business.githubcopilot.com"

# API key for authentication - replace with your actual key
api_key = "<your-github-token>"

# List of available models (auto-populated by the tool)
models = []

# API path to fetch available models
models_path = "/models"

# API path for chat completions
chat_path = "/chat/completions"

# URL to refresh authentication tokens
token_url = "<your-jwt-token>"


[headers]
# HTTP header: user-agent
user-agent = "GitHubCopilotChat/0.28.2"

# HTTP header: editor-version
editor-version = "vscode/1.101.1"


[cached_token]
# Cached authentication token (auto-refreshed)
token = "<your-jwt-token>"

# Token expiration timestamp
expires_at = "2025-08-05T06:25:28Z"


[vars]
